version: '3.1'
services:
    webserver-read:
        image: 'nginx:alpine'
        container_name: nginx-read
        working_dir: /var/www
        volumes:
            - './src:/var/www'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
        links:
            - php-fpm
        networks:
            - global-default

    webserver-record:
        image: 'nginx:alpine'
        container_name: nginx-record
        working_dir: /var/www
        volumes:
            - './src:/var/www'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8001:80'
        links:
            - php-fpm
        networks:
            - global-default

    php-fpm:
        build: docker/php-fpm
        container_name: poc-cqrs
        working_dir: /var/www
        volumes:
            - './src:/var/www'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - global-default
    
    mariadb-master:
        container_name: mariadb-master
        image: mariadb:latest
        volumes:
            - ./docker/var/mariadb-master:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=localstack
        ports:
            - '3306:3306'
        networks:
            - global-default

    mariadb-slave:
        container_name: mariadb-slave
        image: mariadb:latest
        volumes:
            - ./docker/var/mariadb-slave:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=localstack
        ports:
            - '3307:3306'
        depends_on:
            - mariadb-master
        networks:
            - global-default

    adminer:
        image: adminer
        links:
            - mariadb-master
            - mariadb-slave
        ports:
            - 8005:8080
        networks:
            - global-default

networks:
  global-default:
    external: true
